#!/usr/bin/env bash
#Write a while loop bash script that displays Best School 10 times using if
i=0
while [ $i -le 9 ]
do
    echo "Best School"
    if
	[ "$i" -eq 9 ]
    then
	echo "Hi"
    fi
    ((i++))
done
